# Generated by Django 5.1.4 on 2025-01-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membroequipe',
            name='areas',
            field=models.ManyToManyField(blank=True, related_name='membros', to='Users.area'),
        ),
    ]
