# Generated by Django 5.1 on 2025-01-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_membroequipe_areas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membroequipe',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='fotos_membros/'),
        ),
    ]
