# Generated by Django 5.1 on 2025-01-25 01:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('document_username', models.CharField(max_length=255)),
                ('pilot_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('team_members', models.TextField()),
                ('flight_success_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('flight_objective_description', models.TextField()),
                ('results', models.TextField()),
                ('pilot_impressions', models.TextField()),
                ('improvements', models.TextField()),
                ('wind_speed', models.DecimalField(decimal_places=3, max_digits=4)),
                ('wind_direction', models.CharField(max_length=100)),
                ('atmospheric_pressure', models.DecimalField(decimal_places=3, max_digits=4)),
                ('total_takeoff_weight', models.DecimalField(decimal_places=3, max_digits=4)),
                ('flight_cycles', models.PositiveIntegerField()),
                ('telemetry_link', models.URLField()),
                ('occurred_accident', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AccidentLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('damaged_parts', models.TextField()),
                ('damaged_parts_photo', models.URLField()),
                ('was_turbulent', models.BooleanField(default=False)),
                ('pilot_flight_count', models.PositiveIntegerField()),
                ('pilot_impressions', models.TextField()),
                ('id_flightLog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.flightlog')),
            ],
        ),
        migrations.CreateModel(
            name='Minutes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
